### ISSUE TITLE
Please update this package to support laravel 6 and 7

### ISSUE THREAD

**Issue by zersys** [bnbwebexpertise/laravel-google-cloud-print#7]

**Comment by Skintillion** [comment]
It works fine

**Comment by ghost** [comment]
Hello Skintillion.

  You were able to install this on laravel 6 or 7 ?  because i have installed a fresh laravel and then run the composer command to install this package, ant below was the result:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires bnbwebexpertise/laravel-google-cloud-print ^0.1.2 -> satisfiable by bnbwebexpertise/laravel-google-cloud-print[0.1.2].
    - bnbwebexpertise/laravel-google-cloud-print 0.1.2 requires illuminate/config 5.x -> found illuminate/config[v5.0.0, ..., 5.8.x-dev] but it conflicts with another require.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by gabsource** [comment]
Cloud Print, Google’s cloud-based printing solution that has been in beta since 2010, will no longer be supported as of December 31, 2020. Beginning January 1, 2021, devices across all operating systems will no longer be able to print using Google Cloud Print. We recommend that over the next year, you identify an alternative solution and execute a migration strategy.

This package is deprecated.

**Comment by ghost** [comment]
Thanks for answering, regards
